
export const currencyByRupee : Currency [] = [
  {
    name: 'DOLLAR',
    value: 0.00366,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.00336,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.00296,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 0.25354,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.00517,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.00491,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 0.47482,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.00112,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000163,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'AFGHAN AFGHANI',
    value: 0.31791,
    flag: '🇦🇫',
    symbol: '؋',
  },
  {
    name: 'ALBANIAN LEK',
    value: 0.41523,
    flag: '🇦🇱',
    symbol: 'L',
  },
  {
    name: 'ALGERIAN DINAR',
    value: 0.49699,
    flag: '🇩🇿',
    symbol: 'دج',
  },
  {
    name: 'ANGOLAN KWANZA',
    value: 3.00001,
    flag: '🇦🇴',
    symbol: 'Kz',
  },
  {
    name: 'ARGENTINE PESO',
    value: 1.27069,
    flag: '🇦🇷',
    symbol: '$',
  },
  {
    name: 'ARMENIAN DRAM',
    value: 1.39135,
    flag: '🇦🇲',
    symbol: '֏',
  },
  {
    name: 'ARUBAN FLORIN',
    value: 0.00659,
    flag: '🇦🇼',
    symbol: 'ƒ',
  },
  {
    name: 'AZERBAIJANI MANAT',
    value: 0.00623,
    flag: '🇦🇿',
    symbol: 'm',
  },
  {
    name: 'Bahamian Dollar',
    value: 0.00366,
    flag: '🇧🇸',
    symbol: '$',
  },
  {
    name: 'Bahraini Dinar',
    value: 0.00138,
    flag: '🇧🇭',
    symbol: '.د.ب',
  },
  {
    name: 'Bangladeshi Taka',
    value: 0.39842,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'Barbadian Dollar',
    value: 0.00731,
    flag: '🇧🇧',
    symbol: '$',
  },
  {
    name: 'Belarusian Ruble',
    value: 0.01013,
    flag: '🇧🇾',
    symbol: 'Br',
  },
  {
    name: 'Belize Dollar',
    value: 0.00734,
    flag: '🇧🇿',
    symbol: '$',
  },
  {
    name: 'Bermudian Dollar',
    value: 0.00366,
    flag: '🇧🇲',
    symbol: '$',
  },
  {
    name: 'Bhutanese Ngultrum',
    value: 0.30171,
    flag: '🇧🇹',
    symbol: 'Nu.',
  },
  {
    name: 'Bolivian Boliviano',
    value: 0.02529,
    flag: '🇧🇴',
    symbol: 'Bs.',
  },
  {
    name: 'Bosnia-Herzegovina Mark',
    value: 0.00656,
    flag: '🇧🇦',
    symbol: 'KM',
  },
  {
    name: 'Botswana Pula',
    value: 0.04944,
    flag: '🇧🇼',
    symbol: 'P',
  },
  {
    name: 'Brazilian Real',
    value: 0.01769,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'Brunei Dollar',
    value: 0.00487,
    flag: '🇧🇳',
    symbol: '$',
  },
  {
    name: 'Bulgarian Lev',
    value: 0.00657,
    flag: '🇧🇬',
    symbol: 'лв',
  },
  {
    name: 'Burundi Franc',
    value: 10.1658,
    flag: '🇧🇮',
    symbol: 'FBu',
  },
  {
    name: 'CFA Franc BCEAO',
    value: 2.21853,
    flag: '🇨🇫',
    symbol: 'CFA',
  },
  {
    name: 'CFA Franc BEAC',
    value: 2.21853,
    flag: '🇨🇲',
    symbol: 'FCFA',
  },
  {
    name: 'CFP Franc',
    value: 0.40635,
    flag: '🇵🇫',
    symbol: '₣',
  },
  {
    name: 'Cambodian Riel',
    value: 14.8597,
    flag: '🇰🇭',
    symbol: '៛',
  },
  {
    name: 'Cape Verdean Escudo',
    value: 0.36795,
    flag: '🇨🇻',
    symbol: '$',
  },
  {
    name: 'Cayman Islands Dollar',
    value: 0.00305,
    flag: '🇰🇾',
    symbol: '$',
  },
  {
    name: 'Central African CFA Franc',
    value: 2.21853,
    flag: '🇨🇫',
    symbol: 'FCFA',
  },
  {
    name: 'Chilean Peso',
    value: 2.87297,
    flag: '🇨🇱',
    symbol: '$',
  },
  {
    name: 'Chinese Yuan',
    value: 0.02641,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: 'Colombian Peso',
    value: 14.4626,
    flag: '🇨🇴',
    symbol: '$',
  },
  {
    name: 'Comorian Franc',
    value: 1.56628,
    flag: '🇰🇲',
    symbol: 'CF',
  },
  {
    name: 'Congolese Franc',
    value: 9.01457,
    flag: '🇨🇬',
    symbol: 'FC',
  },
  {
    name: 'Costa Rican Colón',
    value: 1.98789,
    flag: '🇨🇷',
    symbol: '₡',
  },
  {
    name: 'Croatian Kuna',
    value: 0.02478,
    flag: '🇭🇷',
    symbol: 'kn',
  },
  {
    name: 'Cuban Peso',
    value: 0.08792,
    flag: '🇨🇺',
    symbol: '$MN',
  },
  {
    name: 'Czech Koruna',
    value: 0.08016,
    flag: '🇨🇿',
    symbol: 'Kč',
  },
  {
    name: 'Danish Krone',
    value: 0.02508,
    flag: '🇩🇰',
    symbol: 'kr',
  },
  {
    name: 'Djiboutian Franc',
    value: 0.64915,
    flag: '🇩🇯',
    symbol: 'Fdj',
  },
  {
    name: 'Dominican Peso',
    value: 0.20463,
    flag: '🇩🇴',
    symbol: 'RD$',
  },
  {
    name: 'East Caribbean Dollar',
    value: 0.00989,
    flag: '🇦🇬',
    symbol: '$',
  },
  {
    name: 'Egyptian Pound',
    value: 0.11345,
    flag: '🇪🇬',
    symbol: '£',
  },
  {
    name: 'Eritrean Nakfa',
    value: 0.05488,
    flag:

 '🇪🇷',
    symbol: 'Nkf',
  },
  {
    name: 'Ethiopian Birr',
    value: 0.20491,
    flag: '🇪🇹',
    symbol: 'Br',
  },
  {
    name: 'Falkland Islands Pound',
    value: 0.00296,
    flag: '🇫🇰',
    symbol: '£',
  },
  {
    name: 'Fijian Dollar',
    value: 0.00817,
    flag: '🇫🇯',
    symbol: '$',
  },
  {
    name: 'Gambian Dalasi',
    value: 0.22476,
    flag: '🇬🇲',
    symbol: 'D',
  },
  {
    name: 'Georgian Lari',
    value: 0.00946,
    flag: '🇬🇪',
    symbol: '₾',
  },
  {
    name: 'Ghanaian Cedi',
    value: 0.04108,
    flag: '🇬🇭',
    symbol: '₵',
  },
  {
    name: 'Gibraltar Pound',
    value: 0.00296,
    flag: '🇬🇮',
    symbol: '£',
  },
  {
    name: 'Guatemalan Quetzal',
    value: 0.02843,
    flag: '🇬🇹',
    symbol: 'Q',
  },
  {
    name: 'Guinean Franc',
    value: 30.2395,
    flag: '🇬🇳',
    symbol: 'FG',
  },
  {
    name: 'Guyanaese Dollar',
    value: 0.76646,
    flag: '🇬🇾',
    symbol: '$',
  },
  {
    name: 'Haitian Gourde',
    value: 0.51599,
    flag: '🇭🇹',
    symbol: 'G',
  },
  {
    name: 'Honduran Lempira',
    value: 0.09009,
    flag: '🇭🇳',
    symbol: 'L',
  },
  {
    name: 'Hungarian Forint',
    value: 1.25571,
    flag: '🇭🇺',
    symbol: 'Ft',
  },
  {
    name: 'Icelandic Króna',
    value: 0.48855,
    flag: '🇮🇸',
    symbol: 'kr',
  },
  {
    name: 'Indian Rupee',
    value: 0.30171,
    flag: '🇮🇳',
    symbol: '₹',
  },
  {
    name: 'Indonesian Rupiah',
    value: 56.244,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'Iranian Rial',
    value: 154.685,
    flag: '🇮🇷',
    symbol: '﷼',
  },
  {
    name: 'Iraqi Dinar',
    value: 4.8156,
    flag: '🇮🇶',
    symbol: 'ع.د',
  },
  {
    name: 'Israeli New Shekel',
    value: 0.01346,
    flag: '🇮🇱',
    symbol: '₪',
  },
  {
    name: 'Jamaican Dollar',
    value: 0.56296,
    flag: '🇯🇲',
    symbol: 'J$',
  },
  {
    name: 'Jordanian Dinar',
    value: 0.00259,
    flag: '🇯🇴',
    symbol: 'د.ا',
  },
  {
    name: 'Kazakhstani Tenge',
    value: 1.65294,
    flag: '🇰🇿',
    symbol: '₸',
  },
  {
    name: 'Kenyan Shilling',
    value: 0.51801,
    flag: '🇰🇪',
    symbol: 'KSh',
  },
  {
    name: 'Kiribati Dollar',
    value: 0.00366,
    flag: '🇰🇮',
    symbol: '$',
  },
  {
    name: 'Kuwaiti Dinar',
    value: 0.00112,
    flag: '🇰🇼',
    symbol: 'د.ك',
  },
  {
    name: 'Kyrgyzstani Som',
    value: 0.32014,
    flag: '🇰🇬',
    symbol: 'с',
  },
  {
    name: 'Lao Kip',
    value: 68.134,
    flag: '🇱🇦',
    symbol: '₭',
  },
  {
    name: 'Latvian Lats',
    value: 0.00236,
    flag: '🇱🇻',
    symbol: 'Ls',
  },
  {
    name: 'Lebanese Pound',
    value: 54.5582,
    flag: '🇱🇧',
    symbol: 'ل.ل',
  },
  {
    name: 'Lesotho Loti',
    value: 0.06498,
    flag: '🇱🇸',
    symbol: 'L',
  },
  {
    name: 'Liberian Dollar',
    value: 0.65672,
    flag: '🇱🇷',
    symbol: '$',
  },
  {
    name: 'Libyan Dinar',
    value: 0.01722,
    flag: '🇱🇾',
    symbol: 'ل.د',
  },
  {
    name: 'Lithuanian Litas',
    value: 0.01144,
    flag: '🇱🇹',
    symbol: 'Lt',
  },
  {
    name: 'Macanese Pataca',
    value: 0.02929,
    flag: '🇲🇴',
    symbol: 'MOP$',
  },
  {
    name: 'Macedonian Denar',
    value: 0.20106,
    flag: '🇲🇰',
    symbol: 'ден',
  },
  {
    name: 'Malagasy Ariary',
    value: 16.3065,
    flag: '🇲🇬',
    symbol: 'Ar',
  },
  {
    name: 'Malawian Kwacha',
    value: 3.75726,
    flag: '🇲🇼',
    symbol: 'MK',
  },
  {
    name: 'Malaysian Ringgit',
    value: 0.01706,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'Maldivian Rufiyaa',
    value: 0.05631,
    flag: '🇲🇻',
    symbol: 'Rf',
  },
  {
    name: 'Mauritanian Ouguiya',
    value: 1.31614,
    flag: '🇲🇷',
    symbol: 'UM',
  },
  {
    name: 'Mauritian Rupee',
    value: 0.15958,
    flag: '🇲🇺',
    symbol: '₨',
  },
  {
    name: 'Mexican Peso',
    value: 0.06392,
    flag: '🇲🇽',
    symbol: '$',
  },
  {
    name: 'Moldovan Leu',
    value: 0.06477,
    flag: '🇲🇩',
    symbol: 'L',
  },
  {
    name: 'Mongolian Tugrik',
    value: 12.5791,
    flag: '🇲🇳',
    symbol: '₮',
  },
  {
    name: 'Moroccan Dirham',
    value: 0.03696,
    flag: '🇲🇦',
    symbol: 'د.م.',
  },
  {
    name: 'Mozambican Metical',
    value: 0.23285,
    flag: '🇲🇿',
    symbol: 'MT',
  },
  {
    name: 'Myanma Kyat',
    value: 7.74628,
    flag: '🇲🇲',
    symbol: 'K',
  },
  {
    name: 'Namibian Dollar',
    value: 0.06498,
    flag: '🇳🇦',
    symbol: 'N$',
  },
  {
    name: 'Nepalese Rupee',
    value: 0.58804,
    flag: '🇳🇵',
    symbol: '₨',
  },
  {
    name: 'Netherlands Antillean Guilder',
    value: 0.00659,
    flag: '🇳🇱',
    symbol: 'ƒ',
  },
  {
    name: 'New Taiwan Dollar',
    value: 0.11298,
    flag: '🇹🇼',
    symbol: 'NT$',
  },
  {
    name: 'New Zealand Dollar',
    value: 0.00578,
    flag: '🇳🇿',
    symbol: 'NZ$',
  },
  {
    name: 'Nicaraguan Córdoba',
    value: 0.13395,
    flag: '🇳🇮',
    symbol: 'C$',
  },
  {
    name: 'Nigerian Naira',
    value: 2.82591,
   

 flag: '🇳🇬',
    symbol: '₦',
  },
  {
    name: 'North Korean Won',
    value: 3.29065,
    flag: '🇰🇵',
    symbol: '₩',
  },
  {
    name: 'Norwegian Krone',
    value: 0.03803,
    flag: '🇳🇴',
    symbol: 'kr',
  },
  {
    name: 'Omani Rial',
    value: 0.00141,
    flag: '🇴🇲',
    symbol: 'ر.ع.',
  },
  {
    name: 'Pakistani Rupee',
    value: 1.00000,
    flag: '🇵🇰',
    symbol: '₨',
  },
  {
    name: 'Panamanian Balboa',
    value: 0.00366,
    flag: '🇵🇦',
    symbol: 'B/.',
  },
  {
    name: 'Papua New Guinean Kina',
    value: 0.01307,
    flag: '🇵🇬',
    symbol: 'K',
  },
  {
    name: 'Paraguayan Guarani',
    value: 26.3633,
    flag: '🇵🇾',
    symbol: '₲',
  },
  {
    name: 'Peruvian Sol',
    value: 0.01337,
    flag: '🇵🇪',
    symbol: 'S/.',
  },
  {
    name: 'Philippine Peso',
    value: 0.20331,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'Polish Zloty',
    value: 0.01510,
    flag: '🇵🇱',
    symbol: 'zł',
  },
  {
    name: 'Qatari Rial',
    value: 0.01334,
    flag: '🇶🇦',
    symbol: 'ر.ق',
  },
  {
    name: 'Romanian Leu',
    value: 0.01668,
    flag: '🇷🇴',
    symbol: 'lei',
  },
  {
    name: 'Rwandan Franc',
    value: 4.17486,
    flag: '🇷🇼',
    symbol: 'FRw',
  },
  {
    name: 'Saint Helena Pound',
    value: 0.00296,
    flag: '🇸🇭',
    symbol: '£',
  },
  {
    name: 'Salvadoran Colón',
    value: 0.03202,
    flag: '🇸🇻',
    symbol: '₡',
  },
  {
    name: 'Samoan Tala',
    value: 0.00973,
    flag: '🇼🇸',
    symbol: 'WS$',
  },
  {
    name: 'São Tomé and Príncipe Dobra',
    value: 83.389,
    flag: '🇸🇹',
    symbol: 'Db',
  },
  {
    name: 'Saudi Riyal',
    value: 0.01372,
    flag: '🇸🇦',
    symbol: 'ر.س',
  },
  {
    name: 'Serbian Dinar',
    value: 0.39152,
    flag: '🇷🇸',
    symbol: 'дин.',
  },
  {
    name: 'Seychellois Rupee',
    value: 0.04856,
    flag: '🇸🇨',
    symbol: '₨',
  },
  {
    name: 'Sierra Leonean Leone',
    value: 36.5282,
    flag: '🇸🇱',
    symbol: 'Le',
  },
  {
    name: 'Singapore Dollar',
    value: 0.00487,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'Solomon Islands Dollar',
    value: 0.02992,
    flag: '🇸🇧',
    symbol: '$',
  },
  {
    name: 'Somali Shilling',
    value: 2.07513,
    flag: '🇸🇴',
    symbol: 'Sh',
  },
  {
    name: 'South African Rand',
    value: 0.06492,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'South Korean Won',
    value: 4.85057,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'South Sudanese Pound',
    value: 2.31814,
    flag: '🇸🇸',
    symbol: 'SS£',
  },
  {
    name: 'Sri Lankan Rupee',
    value: 1.16768,
    flag: '🇱🇰',
    symbol: 'Rs',
  },
  {
    name: 'Sudanese Pound',
    value: 2.20061,
    flag: '🇸🇩',
    symbol: '£',
  },
  {
    name: 'Surinamese Dollar',
    value: 0.13895,
    flag: '🇸🇷',
    symbol: '$',
  },
  {
    name: 'Swazi Lilangeni',
    value: 0.06498,
    flag: '🇸🇿',
    symbol: 'L',
  },
  {
    name: 'Swedish Krona',
    value: 0.03916,
    flag: '🇸🇪',
    symbol: 'kr',
  },
  {
    name: 'Swiss Franc',
    value: 0.00328,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'Syrian Pound',
    value: 28.5557,
    flag: '🇸🇾',
    symbol: '£S',
  },
  {
    name: 'Tajikistani Somoni',
    value: 0.03992,
    flag: '🇹🇯',
    symbol: 'ЅM',
  },
  {
    name: 'Tanzanian Shilling',
    value: 9.14799,
    flag: '🇹🇿',
    symbol: 'Sh',
  },
  {
    name: 'Thai Baht',
    value: 0.12727,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'Tongan Paʻanga',
    value: 0.00865,
    flag: '🇹🇴',
    symbol: 'T$',
  },
  {
    name: 'Trinidad and Tobago Dollar',
    value: 0.02483,
    flag: '🇹🇹',
    symbol: 'TT$',
  },
  {
    name: 'Tunisian Dinar',
    value: 0.01145,
    flag: '🇹🇳',
    symbol: 'د.ت',
  },
  {
    name: 'Turkish Lira',
    value: 0.09123,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'Turkmenistani Manat',
    value: 0.01293,
    flag: '🇹🇲',
    symbol: 'T',
  },
  {
    name: 'Ugandan Shilling',
    value: 13.5604,
    flag: '🇺🇬',
    symbol: 'USh',
  },
  {
    name: 'Ukrainian Hryvnia',
    value: 0.13427,
    flag: '🇺🇦',
    symbol: '₴',
  },
  {
    name: 'United Arab Emirates Dirham',
    value: 0.01343,
    flag: '🇦🇪',
    symbol: 'د.إ',
  },
  {
    name: 'Uruguayan Peso',
    value: 0.14033,
    flag: '🇺🇾',
    symbol: '$U',
  },
  {
    name: 'Uzbekistani Som',
    value: 42.4934,
    flag: '🇺🇿',
    symbol: 'soʻm',
  },
  {
    name: 'Vanuatu Vatu',
    value: 0.43339,
    flag: '🇻🇺',
    symbol: 'VT',
  },
  {
    name: 'Venezuelan Bolívar',
    value: 91.2326,
    flag: '🇻🇪',
    symbol: 'Bs.',
  },
  {
    name: 'Vietnamese Dong',
    value: 86.3763,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'Western Samoan Tala',
    value: 0.00973,
    flag: '🇼🇸',
    symbol: 'WS$',
  },
  {
    name: 'Yemeni Rial',
    value: 0.91608,
    flag: '🇾🇪',
    symbol: '﷼',
  },
  {
    name: 'Zambian Kwacha',
    value: 0.06890,
    flag: '🇿🇲',
    symbol: 'ZK',
  },
  {
    name: 'Zimbabwean Dollar',
    value: 1.32989

,
    flag: '🇿🇼',
    symbol: '$',
  },
]